### ISSUE TITLE
Add health checks to containers

### ISSUE THREAD

**Issue by YuvalAnteby** [YuvalAnteby/Can-I-Run-It#8]
1. Add in docker compose:
```yaml 
services:
  backend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
```

2. Create a health checks route. e.g.
```python
@app.get("/health")
async def health_check():
    return {"status": "ok"}
```
